### ISSUE TITLE
请教一下可以动态使用不同结构体吗

### ISSUE THREAD

**Issue by qianniancn** [rentiansheng/dstruct#8]
```go
type Item struct {
	Id int
	Type string
	Name string
	Desc string
       // 在这块使用不同的结构体
	Details  A or B or C 
}
type A struct {
	//... 
}

type B struct {
	//... 
}
type c struct {
	//... 
}
```

**Comment by rentiansheng** [comment]
这个其实很简单的。 不是项目的实现方式 ，你可以用UnmarshalJSON 来实现

type Detail struct {
     a  A
     b B
    c  C 
}

func(d *Detail) UnmarshalJSON(b []byte)error {
       if err := json.Unmarshal(b, &d.a); err == nil {
          return  nil 
      }
     if err := json.Unmarshal(b, &d.b); err == nil {
          return  nil 
      }
     if err := json.Unmarshal(b, &d.c); err == nil {
          return  nil 
      }

     return errors.New("xxx")
}

func (d Detail) A() A {
     return a
}

func (d Detail) B() B {
     return a
}
func (d Detail) C() C {
     return a
}

**Comment by qianniancn** [comment]
我觉得这种方法不是很优雅，想看看有没有别的解决方法

**Comment by qianniancn** [comment]
```rs
pub struct Item {
    pub id: ItemId,
    pub _type: String,
    pub name: String,
    pub icon: Option<String>,
    pub description: Option<String>,
    #[serde(flatten)]
    pub details: Details,
}
#[serde(tag = "type", content = "details")]
pub enum Details {
    A(ADetails),
    B(BDetails),
    C(CDetails),
}

impl From<Details> for ItemType {
    fn from(d: Details) -> Self {
        match d {
            Details::A(_) => ItemType::A,
            Details::B(_) => ItemType::B,
            Details::C(_) => ItemType::C,
        }
    }
}

```

**Comment by rentiansheng** [comment]
> ```rust
> pub struct Item {
>     pub id: ItemId,
>     pub _type: String,
>     pub name: String,
>     pub icon: Option<String>,
>     pub description: Option<String>,
>     #[serde(flatten)]
>     pub details: Details,
> }
> #[serde(tag = "type", content = "details")]
> pub enum Details {
>     A(ADetails),
>     B(BDetails),
>     C(CDetails),
> }
> 
> impl From<Details> for ItemType {
>     fn from(d: Details) -> Self {
>         match d {
>             Details::A(_) => ItemType::A,
>             Details::B(_) => ItemType::B,
>             Details::C(_) => ItemType::C,
>         }
>     }
> }
> ```

我理解这个是用了语言特性来实现, 功能类似c里面的union类型的功能。 可以用interface 和switch 来实现和模拟类似union。

这个不属于枚举的功能，union 序列化和反序列还是需要开发者自己负责的。

**Comment by qianniancn** [comment]
好的
